version: '3'

services:
  frontend:
    build:
      context: ./frontend  
    ports:
      - "80:80" 
    depends_on:
      - backend  

  backend:
    build:
      context: ./backend  
    ports:
      - "5000:5000" 
    depends_on:
      - db 
    environment:
      DB_HOST: host.docker.internal
      DB_USER: root
      DB_PASSWORD: 11122251@Kavya
      DB_NAME: Employee_Management_System

  db:
    image: mysql:8 
    environment:
      MYSQL_ROOT_PASSWORD: 11122251@Kavya
      MYSQL_DATABASE: Employee_Management_System  
    ports:
      - "3306:3306"  
    volumes:
      - db_data:/var/lib/mysql 
volumes:
  db_data: 
